// anima o css de 3 em 3 seg com o animateCSS

// ESSE CODIGO VAI NA PAGINA DE JS DO SITE
setInterval(()=> {
    animateCSS('#ID DO ELEMENTO OU CLASSE', 'ANIMACAO DO ANIMATECSS'); // ID DO ELEMENTO E NOME DA ANIMAÇÃO EX (heartBeat)
    animateCSS('#ID DO ELEMENTO OU CLASSE', 'ANIMACAO DO ANIMATECSS');
    animateCSS('#ID DO ELEMENTO OU CLASSE', 'ANIMACAO DO ANIMATECSS');
    animateCSS('#ID DO ELEMENTO OU CLASSE', 'ANIMACAO DO ANIMATECSS');
},3000) // TEMPO QUE A ANIMAÇÃO FICARA EM LOOP 3 SEG 

// PARA QUE FUNCIONE NECESSITA DO OUTRO ARQUIVO JS "animateCSS.js"